namespace FSharp.HTML

open Xunit
open Xunit.Abstractions
open System.IO

open FSharp.Idioms.Literal
open FSharp.xUnit

//type HtmlTokenizerTest(output:ITestOutputHelper) =
//    let show res =
//        res
//        |> stringify
//        |> output.WriteLine

//    static let folder = Path.Combine(Dir.TestData,"HtmlTokenizer")

//    // generated by `print files`
//    static let dataSource = SingleDataSource [
//        ]
//    static member keys = dataSource.keys
//    static member get key = dataSource.[key]

//    [<Fact(Skip="get filenames")>] // 
//    member _.``print files``() =
//        let files =
//            Directory.GetFiles(folder)
//            |> Seq.map(fun f -> 
//                let flnm = Path.GetFileName f
//                flnm,[])
//            |> Seq.toList
//        show files

//    [<Theory>]
//    [<MemberData(nameof HtmlTokenizerTest.keys)>]
//    member _.``tokenlist test``(f) =
//        let path = Path.Combine(folder,f)
//        let text = File.ReadAllText(path)
//        let y =
//            text
//            |> HtmlTokenUtils.tokenize TagLeftCompiler.compile 0
//            |> Seq.toList
//        show y
//        let e = HtmlTokenizerTest.get f
//        Should.equal y e
        
